version: "3"

services:
  client:
    build:
      context: .
      dockerfile: cmd/client/Dockerfile
    environment:
      SERVER_HOST: 'server'
      SERVER_PORT: '3333'
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    ports:
      - '3333:3333'
    environment:
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: '3333'
