package manager

func GetWordOfWisdomQuotes() []string {
	return []string{
		"Doubt is the origin of wisdom. Augustine of Hippo",
		"words of wisdom quotes truest resolute determination napoleon bonaparte",
		"The truest wisdom is a resolute determination. Napoleon Bonaparte",
		"words of wisdom quotes science organized knowledge organized life immanuel kant",
		"Science is organized knowledge. Wisdom is organized life. Immanuel Kant",
		"words of wisdom quotes foolishness twin sister witold gombrowicz",
		"Foolishness is a twin sister of wisdom. Witold Gombrowicz",
		"words of wisdom quotes not product schooling the lifelong attempt acquire albert einstein",
		"Wisdom is not a product of schooling but of the lifelong attempt to acquire it. Albert Einstein",
		"Wisdom is the power to put our time and our knowledge to the proper use. Thomas J. Watson",
		"words of wisdom quotes not the man has too little who craves more that poor seneca",
		"It is not the man who has too little, but the man who craves more, that is poor. Seneca",
		"words of wisdom quotes wise man never loses anything has himself michel de montaigne",
		"A wise man never loses anything, if he has himself. Michel de Montaigne",
		"words of wisdom quotes silence sleep nourishes francis bacon",
		"Silence is the sleep that nourishes wisdom. Francis Bacon",
		"words of wisdom quotes discipline vice versa m scott peck",
		"Discipline is wisdom and vice versa. M. Scott Peck",
		"Great wisdom is generous; petty wisdom is contentious. Zhuangzi",
		"words of wisdom sails with wind time john florio wisdom",
		"Wisdom sails with wind and time. John Florio",
		"words of wisdom symptom curiosity evidence calmness perseverance causes experimentation understanding maxime lagace wisdom",
		"A symptom of wisdom is curiosity. The evidence is calmness and perseverance. The causes are experimentation and understanding. Maxime Lagacé",
		"words of wisdom fool known his speech wise man silence pythagoras wisdom",
		"A fool is known by his speech; and a wise man by silence. Pythagoras",
		"words of wisdom most certain sign cheerfulness michel de montaigne wisdom",
		"The most certain sign of wisdom is cheerfulness. Michel de Montaigne",
		"Related quotes and topics: Buddha, Rumi, Einstein",
		"The fool wonders, the wise man asks. Benjamin Disraeli",
		"There is only a finger’s difference between a wise man and a fool. Diogenes",
		"Knowledge speaks, but wisdom listens. Jimi Hendrix Click to tweet",
		"Never say no twice if you mean it. Nassim Nicholas Taleb",
		"Wisdom is nothing but a preparation of the soul, a capacity, a secret art of thinking, feeling and breathing thoughts of unity at every moment of life. Hermann Hesse",
		"Everything comes in time to him who knows how to wait. Leo Tolstoy",
		"Irrigators channel waters; fletchers straighten arrows; carpenters bend wood; the wise master themselves. Buddha",
		"Logic is the beginning of wisdom, not the end. Leonard Nimoy",
		"A lot of wisdom is just realizing the long-term consequences of your actions. The longer term you’re willing to look, the wiser you’re going to seem to everybody around you. Naval Ravikant",
		"A weak reaction is to rush things. A strong reaction is to go slow and steady. Maxime Lagacé",
		"words of wisdom best words are the ones you are ready maxime lagace woman",
		"The best words are the ones you are ready for. Maxime Lagacé",
		"We don’t receive wisdom; we must discover it for ourselves after a journey that no one can take for us or spare us. Marcel Proust",
		"Wisdom ceases to be wisdom when it becomes too proud to weep, too grave to laugh, and too selfish to seek other than itself. Kahlil Gibran",
		"Keep me away from the wisdom which does not cry, the philosophy which does not laugh and the greatness which does not bow before children. Kahlil Gibran",
		"A man has made at least a start on discovering the meaning of human life when he plants shade trees under which he knows full well he will never sit. David Elton Trueblood",
		"Educating the mind without educating the heart is no education at all. Aristotle",
		"Honesty is the first chapter in the book of wisdom. Thomas Jefferson",
		"The motto of chivalry is also the motto of wisdom; to serve all, but love only one. Honoré de Balzac",
		"The wise know they are fools. Fools think they are wise. Maxime Lagacé",
		"Maturity is when you stop being surprised by anything. Wisdom is when you start again. Maxime Lagacé",
		"Wisdom and deep intelligence require an honest appreciation of mystery. Thomas Moore",
		"Wisdom is knowing when you can’t be wise. Paul Engle",
		"Wisdom consists of the anticipation of consequences. Norman Cousins",
		"Wisdom is the knowledge of good and evil, not the strength to choose between the two. John Cheever",
		"The two powers which in my opinion constitute a wise man are those of bearing and forbearing. Epictetus",
		"Wisdom and understanding can only become the possession of individual men by travelling the old road of observation, attention, perseverance, and industry. Samuel Smiles",
		"Wisdom is keeping a sense of fallibility of all our views and opinions. Gerald Brenan",
		"Much wisdom often goes with fewest words. Sophocles Click to tweet",
		"words of wisdom that composes himself wiser composes book benjamin franklin nature hiking sunset mountains",
		"He that composes himself is wiser than he that composes a book. Benjamin Franklin Click to tweet",
		"Do now what your future you will thank you for. Maxime Lagacé",
		"Fast thinking looks cool but it’s deep thinking that makes all the difference. And deep thinking is always slow thinking. @TheAncientSage",
		"Who then is free? The wise man who can command himself. Horace",
		"He who would begun has half done. Dare to be wise; begin. Horace",
		"Man is wise and constantly in quest of more wisdom; but the ultimate wisdom, which deals with beginnings, remains locked in a seed. There it lies, the simplest fact of the universe and at the same time the one which calls forth faith rather than reason. Hal Borland",
		"words of wisdom one part knowing what you dont need anymore letting jane fonda woman sitting street",
		"One part of wisdom is knowing what you don’t need anymore and letting it go. Jane Fonda",
		"First of all, to understand truth you must stand alone, entirely and wholly alone. No Master, no teacher, no guru, no system, no self-discipline will ever lift for you the veil which conceals wisdom. Wisdom is the understanding of enduring values and the living of those values. No one can lead you to wisdom. Jiddu Krishnamurti",
		"The day you plant the seed is not the day you eat the fruit. Paulo Coelho",
		"Men who know themselves are no longer fools. They stand on the threshold of the door of wisdom. Havelock Ellis",
		"Wisdom consists not so much in knowing what to do in the ultimate as knowing what to do next. Herbert Hoover",
		"words of wisdom fool doth think wise man knows himself anatole france tree nature",
		"The fool doth think he is wise, but the wise man knows himself a fool. Anatole France",
		"Silence at the proper season is wisdom, and better than any speech. Plutarch",
		"True wisdom is remembering that in the end, no matter what, everything will be fine. Maxime Lagacé",
		"It’s better to be alone than to spend time with toxic people. It’s better to do nothing than to work on something that doesn’t matter. It’s better to rest than to climb the wrong mountain. James Clear",
		"There is a universal, intelligent, life force that exists within everyone and everything. It resides within each one of use as a deep wisdom, an inner knowing. We can access this wonderful source of knowledge and wisdom through our intuition, an inner sense that tells us what feels right and true for us at any given moment. Shakti Gawain",
		"If the fool would persist in his folly he would become wise. William Blake",
		"Knowledge shrinks as wisdom grows. Alfred North Whitehead",
		"The more you know the less you say. Sahil Lavingia (Source)",
		"Don’t try to become, let go of who you’re not. Maxime Lagacé",
		"The truest sayings are paradoxical. Lao Tzu (Tao Te Ching)",
		"Knowledge comes, but wisdom lingers. Alfred Lord Tennyson",
		"One principle eliminates a thousand decisions. Johnny Uzan",
		"Wisdom comes by disillusionment. George Santayana",
		"Wisdom has never made a bigot, but learning has. Josh Billings",
		"Never does nature say one thing and wisdom another. Juvenal",
		"The wisest of the wise may err. Aeschylus",
		"Pain is the doorway to wisdom and to truth. Keith Miller",
		"No man was ever wise by chance. Seneca",
		"Wisdom is knowledge which has become a part of one’s being. Orison Swett Marden",
		"Kindness is wisdom. Philip James Bailey",
		"Wisdom begins in wonder. Socrates",
		"Wisdom outweighs any wealth. Sophocles",
		"The wise are those who know the Self. Sri Sathya Sai Baba",
		"I would rather be a man of paradoxes than a man of prejudices. Jean-Jacques Rousseau",
		"Wisdom comes from experience. Experience is often a result of lack of wisdom. Terry Pratchett",
		"The wise man belongs to all countries, for the home of a great soul is the whole world. Democritus",
		"For everything you have missed, you have gained something else, and for everything you gain, you lose something else. Ralph Waldo Emerson",
		"The best words of wisdom will create confusion, action, understanding and ultimately, peace. Maxime Lagacé",
		"If you succeed in judging yourself rightly, then you are indeed a man of true wisdom. Antoine de Saint-Exupéry",
		"Cleverness is like a lens with a very sharp focus. Wisdom is more like a wide-angle lens. Edward de Bono",
		"It is unwise to be too sure of one’s own wisdom. It is healthy to be reminded that the strongest might weaken and the wisest might err. Mahatma Gandhi",
		"We will be known forever by the tracks we leave. Dakota (Native American saying)",
		"Has fortune dealt you some bad cards. Then let wisdom make you a good gamester. Francis Quarles",
		"The function of wisdom is to discriminate between good and evil. Marcus Tullius Cicero",
		"Talent is like the marksman who hits a target which others cannot reach; genius is like the marksman who hits a target… which others cannot even see. Arthur Schopenhauer",
		"Contemplation and wisdom are highest achievements and man is not totally at home with them. Gabriel Marcel",
		"Real wisdom is not the knowledge of everything, but the knowledge of which things in life are necessary, which are less necessary, and which are completely unnecessary to know. Leo Tolstoy",
		"Wisdom is knowing what to ignore. Shane Parrish (Source)",
		"Wisdom is seeing wounds and obstacles as blessings. Maxime Lagacé",
		"It’s wisdom to recognize necessity, when all other courses have been weighed, though as folly it may appear to those who cling to false hope. J. R. R. Tolkien",
		"The small wisdom is like water in a glass: clear, transparent, pure. The great wisdom is like the water in the sea: dark, mysterious, impenetrable. Rabindranath Tagore",
		"Innocence dwells with wisdom, but never with ignorance. William Blake",
		"Wisdom is the knowledge of good and evil, not the strength to choose between the two. John Cheever",
		"Words should be weighed, not counted. Yiddish proverb",
	}
}
